= NetRelay

*web application framework based on vert.x-web*

NetRelay is a web application framework based on vert.x and vert.x-web. It is styled to allow a configurable, transparent 
definition of routings inside a web application by using adjustable, reusable instances, the Controllers. Additionaly NetRelay 
predefines the MVC-concept

Key features

* configurable, reusable Controllers, which are executed on a suitable route
* structures the MVC concept
* lots of ready to use Controllers like Persistence-Controller, AuthenticationController, RegisterController etc.
* structures the use of configurable, reusable processors, which are executed regular as timer
* uses vertx-pojo-mapper

If you are searching for a very quick entry with a prepared, ready to use project based on NetRelay, you should go to 

*link:https://github.com/BraintagsGmbH/NetRelay-Demoproject[ Quickstart with NetRelay-Demoproject]*

If you want to go more into detail, go here:

* link:src/docs/asciidoc/java/index.adoc[ java ]



